name: PluginTemplate
version: '${project.version}'
main: com.rednetty.plugintemplate.PluginTemplate
api-version: '1.20'
authors: [RedNetty]
description: A modern, comprehensive Spigot plugin template
website: https://rednetty.com

depend: []
softdepend: [Vault, PlaceholderAPI]

commands:
  plugintemplate:
    description: Main plugin command
    aliases: [pt, template]
    usage: /plugintemplate <subcommand>
    permission: plugintemplate.use

permissions:
  plugintemplate.*:
    description: All plugin permissions
    children:
      plugintemplate.use: true
      plugintemplate.admin: true
      plugintemplate.reload: true
  plugintemplate.use:
    description: Basic plugin usage
    default: true
  plugintemplate.admin:
    description: Administrative commands
    default: op
  plugintemplate.reload:
    description: Reload plugin configuration
    default: op
